# Generated by Django 6.0 on 2025-12-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvaluationFormula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lab_count", models.PositiveIntegerField()),
                ("lab_max_score", models.PositiveIntegerField()),
                ("exam_max_score", models.PositiveIntegerField()),
                ("penalty_per_missed", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
