variable "table_name" {
  description = "The name of the DynamoDB table (generated by null-label)"
  type        = string
}

variable "hash_key" {
  description = "The attribute to use as the hash (partition) key"
  type        = string
  default     = "id"
}